### ISSUE TITLE
How do you use the docker distribution?

### ISSUE THREAD

**Issue by StoyanStAtanasov** [meta-llama/llama-stack#106]
`docker run  llamastack/llamastack-local-gpu:latest` does nothing

**Comment by yanxi0830** [comment]
Thanks for the question! Could you try the following commands, and follow the instructions in this section? https://github.com/meta-llama/llama-stack-apps/tree/main?tab=readme-ov-file#alternative-downloading-pre-built-docker-image

```
docker image pull llamastack/llamastack-local-gpu
llama stack configure llamastack-local-gpu
llama stack run local-gpu
```

**Comment by StoyanStAtanasov** [comment]
Thanks for the quick answer.
Oh, you use the cli on your host to configure the docker container. This was not clear to me from the docs.

**Comment by StoyanStAtanasov** [comment]
Still not working:
C:\workspace> cd .\llama\
C:\workspace\llama> python -m venv .venv
C:\workspace\llama> .\.venv\Scripts\Activate.ps1
(.venv) C:\workspace\llama> pip install llama-stack
(.venv) PS C:\workspace\llama> llama stack configure llamastack-local-gpu
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\workspace\llama\.venv\Scripts\llama.exe\__main__.py", line 7, in <module>
  File "C:\workspace\llama\.venv\Lib\site-packages\llama_stack\cli\llama.py", line 44, in main
    parser.run(args)
  File "C:\workspace\llama\.venv\Lib\site-packages\llama_stack\cli\llama.py", line 38, in run
    args.func(args)
  File "C:\workspace\llama\.venv\Lib\site-packages\llama_stack\cli\stack\configure.py", line 45, in _run_stack_configure_cmd
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
(.venv) PS C:\workspace\llama>

**Comment by ashwinb** [comment]
I think you need to install `setuptools` also. We probably need to add it as a dependency in requirements.txt.

On Sep 25, 2024, at 5:32 PM, Stoyan Atanasov ***@***.***> wrote:

Still not working: C: \workspace> cd .\llama C: \workspace\llama> python -m venv .venv C: \workspace\llama> .. venv\Scripts\Activate. ps1 (. venv) C: \workspace\llama> pip install llama-stack (. venv) PS C: \workspace\llama> llama stack



Still not working:
C:\workspace> cd .\llama
C:\workspace\llama> python -m venv .venv
C:\workspace\llama> ..venv\Scripts\Activate.ps1
(.venv) C:\workspace\llama> pip install llama-stack
(.venv) PS C:\workspace\llama> llama stack configure llamastack-local-gpu
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in run_code
File "C:\workspace\llama.venv\Scripts\llama.exe_main.py", line 7, in
File "C:\workspace\llama.venv\Lib\site-packages\llama_stack\cli\llama.py", line 44, in main
parser.run(args)
File "C:\workspace\llama.venv\Lib\site-packages\llama_stack\cli\llama.py", line 38, in run
args.func(args)
File "C:\workspace\llama.venv\Lib\site-packages\llama_stack\cli\stack\configure.py", line 45, in _run_stack_configure_cmd
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
(.venv) PS C:\workspace\llama>

**Comment by StoyanStAtanasov** [comment]
Sure I will try, but can you guys make it so it is all already installed in a container? Can we just download a distribution, configure and use? Maybe I should create another issue?

Still not working:

(.venv) PS C:\Users\stoia\workspace\llama-stack>  llama stack configure llamastack-local-gpu
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\stoia\workspace\llama-stack\.venv\Scripts\llama.exe\__main__.py", line 7, in <module>
  File "C:\Users\stoia\workspace\llama-stack\.venv\Lib\site-packages\llama_stack\cli\llama.py", line 44, in main
    parser.run(args)
  File "C:\Users\stoia\workspace\llama-stack\.venv\Lib\site-packages\llama_stack\cli\llama.py", line 38, in run
    args.func(args)
  File "C:\Users\stoia\workspace\llama-stack\.venv\Lib\site-packages\llama_stack\cli\stack\configure.py", line 45, in _run_stack_configure_cmd
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
(.venv) PS C:\Users\stoia\workspace\llama-stack> python.exe -m pip install --upgrade setuptools
Collecting setuptools
  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
Using cached setuptools-75.1.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
Successfully installed setuptools-75.1.0
(.venv) PS C:\Users\stoia\workspace\llama-stack>  llama stack configure llamastack-local-gpu
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\stoia\workspace\llama-stack\.venv\Scripts\llama.exe\__main__.py", line 7, in <module>
  File "C:\Users\stoia\workspace\llama-stack\.venv\Lib\site-packages\llama_stack\cli\llama.py", line 44, in main
    parser.run(args)
  File "C:\Users\stoia\workspace\llama-stack\.venv\Lib\site-packages\llama_stack\cli\llama.py", line 38, in run
    args.func(args)
  File "C:\Users\stoia\workspace\llama-stack\.venv\Lib\site-packages\llama_stack\cli\stack\configure.py", line 50, in _run_stack_configure_cmd
    from llama_stack.distribution.build import ImageType
  File "C:\Users\stoia\workspace\llama-stack\.venv\Lib\site-packages\llama_stack\distribution\build.py", line 15, in <module>
    from llama_stack.distribution.utils.exec import run_with_pty
  File "C:\Users\stoia\workspace\llama-stack\.venv\Lib\site-packages\llama_stack\distribution\utils\exec.py", line 9, in <module>
    import pty
  File "C:\Python312\Lib\pty.py", line 12, in <module>
    import tty
  File "C:\Python312\Lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
(.venv) PS C:\Users\stoia\workspace\llama-stack> python.exe -m pip install --upgrade termios
ERROR: Could not find a version that satisfies the requirement termios (from versions: none)
ERROR: No matching distribution found for termios
(.venv) PS C:\Users\stoia\workspace\llama-stack>

**Comment by russellb** [comment]
> Sure I will try, but can you guys make it so it is all already installed in a container? Can we just download a distribution, configure and use? Maybe I should create another issue?

A recent PR made using a docker based distribution easier where you can just pull and run a container instead of having to install the `llama` tool first. Maybe you could give it a try?

https://github.com/meta-llama/llama-stack/pull/159

**Comment by nathan-weinberg** [comment]
This may be worth closing, given @russellb's comment above and the lack of any response since October
