### ISSUE TITLE
stack tool cannot support large models with a .pth extension downloaded from Meta

### ISSUE THREAD

**Issue by Itime-ren** [meta-llama/llama-stack#190]
The stack tool cannot support large models with a .pth extension downloaded from Meta. It throws an error during runtime. Does it have to use models downloaded from Hugging Face? Is this setup unreasonable? The runtime error is as follows:

(stack) root@720:~/.llama/checkpoints/Llama3.1-8B-Instruct# llama stack run my-local-stack
Resolved 8 providers in topological order
  Api.models: routing_table
  Api.inference: router
  Api.shields: routing_table
  Api.safety: router
  Api.memory_banks: routing_table
  Api.memory: router
  Api.agents: meta-reference
  Api.telemetry: meta-reference

Traceback (most recent call last):
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 351, in <module>
    fire.Fire(main)
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 288, in main
    impls, specs = asyncio.run(resolve_impls_with_routing(config))
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack/distribution/resolver.py", line 104, in resolve_impls_with_routing
    impl = await instantiate_provider(spec, deps, configs[api])
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack/distribution/resolver.py", line 174, in instantiate_provider
    impl = await instantiate_provider(
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack/distribution/resolver.py", line 192, in instantiate_provider
    impl = await fn(*args)
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/inference/__init__.py", line 18, in get_provider_
impl
    await impl.initialize()
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/inference/inference.py", line 38, in initialize
    self.generator = LlamaModelParallelGenerator(self.config)
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/inference/model_parallel.py", line 72, in __init_
_
    self.formatter = ChatFormat(Tokenizer(tokenizer_path))
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/llama_models/llama3/api/tokenizer.py", line 77, in __init__
    mergeable_ranks = load_tiktoken_bpe(model_path)
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/tiktoken/load.py", line 145, in load_tiktoken_bpe
    return {
  File "/home/miniconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/tiktoken/load.py", line 147, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
ValueError: not enough values to unpack (expected 2, got 1)
Error occurred in script at line: 40

**Comment by raghotham** [comment]
You should be able to use models downloaded from Meta with Llama Stack. Also, looks like you are trying one of the smaller models: Llama3.1-8B-Instruct (not 70B or 405B). Can you share details of your setup?

**Comment by Itime-ren** [comment]
> You should be able to use models downloaded from Meta with Llama Stack. Also, looks like you are trying one of the smaller models: Llama3.1-8B-Instruct (not 70B or 405B). Can you share details of your setup?

I got the same issue by docker image from llamastack/llamastack-local-gpu
https://github.com/meta-llama/llama-stack/issues/242
