### ISSUE TITLE
Failed when run local-ollama

### ISSUE THREAD

**Issue by alexhegit** [meta-llama/llama-stack#228]
Steps:
1. build the local-ollama
$ llama stack build --config llama_stack/distribution/templates/local-ollama-build.yaml
2. configure
$ llama stack configure local-ollama
3.  run
$ llama stack run local-ollama --port 5566

Error log
```
(LlamaStack) amd@tw024:~/alehe/llama-stack$ llama stack run local-ollama --port 5566
Traceback (most recent call last):
  File "/home/amd/.local/bin/llama", line 8, in <module>
    sys.exit(main())
  File "/home/amd/alehe/llama-stack/llama_stack/cli/llama.py", line 44, in main
    parser.run(args)
  File "/home/amd/alehe/llama-stack/llama_stack/cli/llama.py", line 38, in run
    args.func(args)
  File "/home/amd/alehe/llama-stack/llama_stack/cli/stack/run.py", line 79, in _run_stack_run_cmd
    config = StackRunConfig(**yaml.safe_load(f))
  File "/home/amd/.local/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 10 validation errors for StackRunConfig
api_providers.agents.GenericProviderConfig.provider_type
  Field required [type=missing, input_value={'provider_id': 'meta-ref...a/runtime/kvstore.db'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
api_providers.agents.PlaceholderProviderConfig.providers
  Field required [type=missing, input_value={'provider_id': 'meta-ref...a/runtime/kvstore.db'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
api_providers.telemetry.GenericProviderConfig.provider_type
  Field required [type=missing, input_value={'provider_id': 'meta-reference', 'config': {}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
api_providers.telemetry.PlaceholderProviderConfig.providers
  Field required [type=missing, input_value={'provider_id': 'meta-reference', 'config': {}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
routing_table.inference.0.provider_type
  Field required [type=missing, input_value={'provider_id': 'remote::...a-Llama3.1-8B-Instruct'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
routing_table.memory.0.provider_type
  Field required [type=missing, input_value={'provider_id': 'meta-ref...'routing_key': 'vector'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
routing_table.safety.0.provider_type
  Field required [type=missing, input_value={'provider_id': 'meta-ref...ing_key': 'llama_guard'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
routing_table.safety.1.provider_type
  Field required [type=missing, input_value={'provider_id': 'meta-ref...': 'code_scanner_guard'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
routing_table.safety.2.provider_type
  Field required [type=missing, input_value={'provider_id': 'meta-ref...ey': 'injection_shield'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
routing_table.safety.3.provider_type
  Field required [type=missing, input_value={'provider_id': 'meta-ref...ey': 'jailbreak_shield'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

**Comment by alexhegit** [comment]
Fixed by 'pip install -r requirement.txt' in llama-stack (git repo)
