### ISSUE TITLE
Fail to start basic inference server example

### ISSUE THREAD

**Issue by astroalek** [meta-llama/llama-stack#25]
I tried to execute the procedure specified in docs/cli_reference.md but I got an error, I'm gonna paste the console content from the last part of the output of the command `llama distribution install --spec local --name local_llama_8b_instruct`

```
Successfully setup distribution environment. Configuring...
Configuring API surface: inference
Enter value for model (default: Meta-Llama3.1-8B-Instruct): 
Enter value for quantization (optional): 
Enter value for torch_seed (optional): 
Enter value for max_seq_len (required): 4096
Enter value for max_batch_size (default: 1): 

Configuring API surface: safety
Do you want to configure llama_guard_shield? (y/n): n
Do you want to configure prompt_guard_shield? (y/n): n

Configuring API surface: agentic_system

YAML configuration has been written to /home/ubuntu/.llama/distributions/local_llama_8b_instruct/config.yaml
Distribution `local_llama_8b_instruct` (with spec local) has been installed successfully!
ubuntu@ip-hidden:~$ llama distribution start --name local_llama_8b_instruct --port 5000
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
/opt/conda/envs/local_llama_8b_instruct/lib/python3.10/site-packages/torch/__init__.py:955: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
E0812 17:24:42.239000 139992924231488 torch/distributed/elastic/multiprocessing/api.py:702] failed (exitcode: -9) local_rank: 0 (pid: 1822) of fn: worker_process_entrypoint (start_method: fork)
E0812 17:24:42.239000 139992924231488 torch/distributed/elastic/multiprocessing/api.py:702] Traceback (most recent call last):
E0812 17:24:42.239000 139992924231488 torch/distributed/elastic/multiprocessing/api.py:702]   File "/opt/conda/envs/local_llama_8b_instruct/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 659, in _poll
E0812 17:24:42.239000 139992924231488 torch/distributed/elastic/multiprocessing/api.py:702]     self._pc.join(-1)
E0812 17:24:42.239000 139992924231488 torch/distributed/elastic/multiprocessing/api.py:702]   File "/opt/conda/envs/local_llama_8b_instruct/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 170, in join
E0812 17:24:42.239000 139992924231488 torch/distributed/elastic/multiprocessing/api.py:702]     raise ProcessExitedException(
E0812 17:24:42.239000 139992924231488 torch/distributed/elastic/multiprocessing/api.py:702] torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL
Process ForkProcess-1:
Traceback (most recent call last):
  File "/opt/conda/envs/local_llama_8b_instruct/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/local_llama_8b_instruct/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/local_llama_8b_instruct/lib/python3.10/site-packages/llama_toolchain/inference/meta_reference/parallel_utils.py", line 175, in launch_dist_group
    elastic_launch(launch_config, entrypoint=worker_process_entrypoint)(
  File "/opt/conda/envs/local_llama_8b_instruct/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/local_llama_8b_instruct/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
==========================================================
worker_process_entrypoint FAILED
----------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
----------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-12_17:24:42
  host      : ip-hidden
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 1822)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 1822
==========================================================

Ctrl-C detected. Aborting...
```

This is the output of `nvidia-smi`:

```
Mon Aug 12 17:26:34 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10G                    On  | 00000000:00:1E.0 Off |                    0 |
|  0%   29C    P8               9W / 300W |      0MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

Is there any other software/hardware requirement not specified in the doc that can cause this?

Thanks!

**Comment by astroalek** [comment]
I installed the CLI using the command `pip install llama-toolchain` and the `pip list` shows that the version is 0.0.4 so I don't think it's a version problem.

**Comment by ashwinb** [comment]
Puzzling. It seems like the forked process received a `SIGKILL` from somewhere -- it is possible this is just an OOM because we are consuming more memory than we should be. Looking into it.

**Comment by ashwinb** [comment]
Can you see if https://github.com/meta-llama/llama-stack/pull/30/ helps?

**Comment by astroalek** [comment]
Stille getting the same error running the same command after executing `pip install llama-toolchain -U` and successfully upgrading to version 0.0.5
