### ISSUE TITLE
Ollama inference : llama3.1:8b-instruct-fp16 , what name is it in the python stack client ?

### ISSUE THREAD

**Issue by Pentar0o** [meta-llama/llama-stack#258]
Hy,

I'm using ollama with the llama3.1:8b-instruct-fp16 model as the documentation says it's the only one recognized and working but when I'm trying to use the python client, the llama stack server says that the model is not recognized, so what's the correct label to put in the line model="Llama3.1-8B-Instruct" ?

There is my code : 

from llama_stack_client import LlamaStackClient
from llama_stack_client.types import UserMessage

host = '127.0.0.1'
port = 5000

client = LlamaStackClient(
    base_url=f"http://{host}:{port}",
)

response = client.inference.chat_completion(
    messages=[
        UserMessage(
            content="Quelle est la capitale de paris ?",
            role="user",
        ),
    ],
    model="Llama3.1-8B-Instruct",
    stream=False,
)
print(response)

There is on the llama stack side :
Traceback (most recent call last):
File "/home/penta/anaconda3/envs/llamastack-Cortana/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 239, in endpoint
value = func(**kwargs)
File "/home/penta/anaconda3/envs/llamastack-Cortana/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 94, in chat_completion
provider = self.routing_table.get_provider_impl(model)
File "/home/penta/anaconda3/envs/llamastack-Cortana/lib/python3.10/site-packages/llama_stack/distribution/routers/routing_tables.py", line 91, in get_provider_impl
raise ValueError(f"{routing_key} not registered")
ValueError: Llama3.1-8B-Instruct not registered

I've tried several variations like llama3.1:8b-instruct-fp16 with and without uppercase but nothing is working...

Any help appreciated.

**Comment by Pentar0o** [comment]
There is on the llama stack side : 
Traceback (most recent call last):
  File "/home/penta/anaconda3/envs/llamastack-Cortana/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 239, in endpoint
    value = func(**kwargs)
  File "/home/penta/anaconda3/envs/llamastack-Cortana/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 94, in chat_completion
    provider = self.routing_table.get_provider_impl(model)
  File "/home/penta/anaconda3/envs/llamastack-Cortana/lib/python3.10/site-packages/llama_stack/distribution/routers/routing_tables.py", line 91, in get_provider_impl
    raise ValueError(f"`{routing_key}` not registered")
ValueError: `Llama3.1-8B-Instruct` not registered 

I've tried several variations like llama3.1:8b-instruct-fp16 with and without uppercase but nothing is working...

Any help appreciated.

**Comment by yanxi0830** [comment]
Thanks for the question! You may check what are the supported models via `llama-stack-client models list`. 
E.g. you will see a table: 
```
$ llama-stack-client models list
+----------------------+----------------------+---------------+----------------------------------------------------------+
| identifier           | llama_model          | provider_id   | metadata                                                 |
+======================+======================+===============+==========================================================+
| Llama3.1-8B-Instruct | Llama3.1-8B-Instruct | remote::tgi   | {'huggingface_repo': 'meta-llama/Llama-3.1-8B-Instruct'} |
+----------------------+----------------------+---------------+----------------------------------------------------------+
```

You may use the `identifier` column to see what you should put for `models`. For `llama3.1:8b-instruct-fp16` in ollama, it should be `Llama3.1-8B-Instruct`.

**Comment by Pentar0o** [comment]
Perfect ! Runs like a charm now ! Thank you !

**Comment by yanxi0830** [comment]
Great!
