### ISSUE TITLE
llama model template --name tool-message-success fails

### ISSUE THREAD

**Issue by HamidShojanazeri** [meta-llama/llama-stack#28]
seems this template requires some updates.

```
(llama-stack) bash-5.1$ llama model template --name tool-message-success
Traceback (most recent call last):
  File "/home/hamidnazeri/.conda/envs/llama-stack/bin/llama", line 8, in <module>
    sys.exit(main())
  File "/home/hamidnazeri/llama-stack/llama_toolchain/cli/llama.py", line 54, in main
    parser.run(args)
  File "/home/hamidnazeri/llama-stack/llama_toolchain/cli/llama.py", line 48, in run
    args.func(args)
  File "/home/hamidnazeri/llama-stack/llama_toolchain/cli/model/template.py", line 58, in _run_model_template_cmd
    template, tokens_info = render_jinja_template(args.name)
  File "/home/hamidnazeri/.conda/envs/llama-stack/lib/python3.10/site-packages/llama_models/llama3_1/api/interface.py", line 210, in render_jinja_template
    raise ValueError(f"No template found for `{name}`")
ValueError: No template found for `tool-message-success`

```

**Comment by hardikjshah** [comment]
It should be 
```
llama model template --name tool-success
``` 
you can get the full list of supported templates by running `llama model template`
