### ISSUE TITLE
[bug] VLLM inference throwing validation error for CompletionMessage

### ISSUE THREAD

**Issue by subramen** [meta-llama/llama-stack#305]
Running example https://github.com/meta-llama/llama-stack-apps/blob/main/examples/agents/rag_with_memory_bank.py on VLLM stack throws the following error:

```
Batches: 100% 1/1 [00:00<00:00, 138.38it/s]
role='user' content='Answer in one sentence - how to use LoRA?' context='Here are the retrieved documents for relevant context:\n=== START-RETRIEVED-CONTEXT ===\n\nid:num-5; content:.. _lora_finetune_label:\n\n============================\nFine-Tuning Llama2 with LoRA\n============================\n\nThis guide will teach you about `LoRA <https://arxiv.org/abs/2106.09685>`_, a parameter-efficient finetuning technique,\nand show you how you can use torchtune to finetune a Llama2 model with LoRA.\...<more>...lue of :code:`nproc_per_node` depending on (a) the number of GPUs you have available,\n    and (b) the memory constraints of your hardware.\n\nThe preceding command will run a LoRA finetune with torchtune\'s factory settings, but we may want to experiment a bit.\nLet\'s take a closer look at some of the :code:`lora_finetune_distributed` config.\n\n.. code-block:: yaml\n\n  # Model Arguments\n  model:\n    _component_: lora_llama2_7b\n    lora_attn_modules: [\'\n\n=== END-RETRIEVED-CONTEXT ===\n'
INFO 10-24 21:34:54 async_llm_engine.py:207] Added request 7f3775c41ba8494faf7ae5fac8064924.
INFO 10-24 21:34:54 metrics.py:349] Avg prompt throughput: 5.5 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.6%, CPU KV cache usage: 0.0%.
INFO 10-24 21:34:55 async_llm_engine.py:175] Finished request 7f3775c41ba8494faf7ae5fac8064924.
Traceback (most recent call last):
  File "/home/ubuntu/subramen/llama-stack/llama_stack/distribution/server/server.py", line 206, in sse_generator
    async for item in await event_gen:
  File "/home/ubuntu/subramen/llama-stack/llama_stack/providers/impls/meta_reference/agents/agents.py", line 138, in _create_agent_turn_streaming
    async for event in agent.create_and_execute_turn(request):
  File "/home/ubuntu/subramen/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 179, in create_and_execute_turn
    async for chunk in self.run(
  File "/home/ubuntu/subramen/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 252, in run
    async for res in self._run(
  File "/home/ubuntu/subramen/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 427, in _run
    async for chunk in await self.inference_api.chat_completion(
  File "/home/ubuntu/subramen/llama-stack/llama_stack/distribution/routers/routers.py", line 96, in <genexpr>
    return (chunk async for chunk in await provider.chat_completion(**params))
  File "/home/ubuntu/subramen/llama-stack/llama_stack/providers/impls/vllm/vllm.py", line 231, in _stream_chat_completion
    async for chunk in process_chat_completion_stream_response(
  File "/home/ubuntu/subramen/llama-stack/llama_stack/providers/utils/inference/openai_compat.py", line 202, in process_chat_completion_stream_response
    message = formatter.decode_assistant_message_from_content(buffer, stop_reason)
  File "/opt/conda/envs/llamastack-vllm-stack/lib/python3.10/site-packages/llama_models/llama3/api/chat_format.py", line 208, in decode_assistant_message_from_content
    return CompletionMessage(
  File "/opt/conda/envs/llamastack-vllm-stack/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CompletionMessage
stop_reason
  Input should be 'end_of_turn', 'end_of_message' or 'out_of_tokens' [type=enum, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/enum
```

Stack config:
```
conda_env: vllm-stack
apis:
- inference
- safety
- agents
- memory
- telemetry
providers:
  inference:
  - provider_id: vllm
    provider_type: vllm
    config:
      model: Llama3.1-8B-Instruct
      tensor_parallel_size: 4
  safety:
  - provider_id: meta-reference
    provider_type: meta-reference
    config:
      llama_guard_shield: null
      enable_prompt_guard: false
  agents:
  - provider_id: meta-reference
    provider_type: meta-reference
    config:
      persistence_store:
        namespace: null
        type: sqlite
        db_path: /home/ubuntu/.llama/runtime/kvstore.db
  memory:
  - provider_id: meta-reference
    provider_type: meta-reference
    config: {}
  telemetry:
  - provider_id: meta-reference
    provider_type: meta-reference
    config: {}
```

**Comment by ashwinb** [comment]
Fixed and improved a bunch of stuff: 

https://github.com/meta-llama/llama-stack/commit/70d59b0f5de914bea011ae5256f3a24330dbb83b

**Comment by ashwinb** [comment]
Added a config option `enforce_eager:` which you should set to `true` if you want start up to be faster (during iteration) but that comes at the cost of slower inference calls later
