### ISSUE TITLE
Ollama inference issue - llama3.2 not registered

### ISSUE THREAD

**Issue by akhtet** [meta-llama/llama-stack#332]
### System Info

Ubuntu, CPU only, Conda, Python 3.10

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

I am running a single node stack with Ollama remote on conda, and encountered a problem with the LlamaStack inference API using the Python Client.

``` 
llama_stack_client.BadRequestError: 
Error code: 400 - {'detail': 'Invalid value: `llama3.2` not registered. Make sure there is an Inference provider serving this model.'}
```

However, I have already setup Ollama and can access the model through Ollama REST API. 
The following command accesses the Ollama REST API directly and it works.
```
curl http://localhost:11434/api/chat -d '{
  "model": "llama3.2",
  "messages": [
    { "role": "user", "content": "why is the sky blue?" }
  ]
}'
```

LlamaStack is also setup with Ollama endpoint.
```
 inner-inference => remote::ollama
 inner-memory => meta-reference
 models => __routing_table__
 inference => __autorouted__
 inner-safety => meta-reference
 shields => __routing_table__
 safety => __autorouted__
 memory_banks => __routing_table__
 memory => __autorouted__
 agents => meta-reference
 telemetry => meta-reference
 inspect => __builtin__
```

### Error logs

```
Traceback (most recent call last):
  File "/home/aidev/llama-stack-test/test2.py", line 5, in <module>
    response = client.inference.chat_completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aidev/miniconda3/lib/python3.12/site-packages/llama_stack_client/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aidev/miniconda3/lib/python3.12/site-packages/llama_stack_client/resources/inference/inference.py", line 220, in chat_completion
    self._post(
  File "/home/aidev/miniconda3/lib/python3.12/site-packages/llama_stack_client/_base_client.py", line 1261, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aidev/miniconda3/lib/python3.12/site-packages/llama_stack_client/_base_client.py", line 953, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/aidev/miniconda3/lib/python3.12/site-packages/llama_stack_client/_base_client.py", line 1056, in _request
    raise self._make_status_error_from_response(err.response) from None
llama_stack_client.BadRequestError: Error code: 400 - {'detail': 'Invalid value: `llama3.2` not registered. Make sure there is an Inference provider serving this model.'}
```

### Expected behavior

The test client python code is quite simple, yet the model isn't recognized by LlamaStack Service.

```
from llama_stack_client import LlamaStackClient

client = LlamaStackClient(base_url="http://localhost:5000")
user_input = "Hello! How are you?"
response = client.inference.chat_completion(
        model="llama3.2",
                messages=[{"role": "user", "content": user_input}],
                    stream=False
                    )

print("Bot:", response.text)
```
```
llama_stack_client.BadRequestError: Error code: 400 - {'detail': 'Invalid value: `llama3.2` not registered. Make sure there is an Inference provider serving this model.'}
```

**Comment by geronimo** [comment]
+1

I have the same issue, regardless of what model I try to use in Ollama.

**Comment by yanxi0830** [comment]
See the comment here: https://github.com/meta-llama/llama-stack/issues/258#issuecomment-2417744998 for working with alternative models with ollama. 

Could you also attach your `run.yaml` file that you are running with?

**Comment by geronimo** [comment]
@yanxi0830 I'm using `llama3.1:8b-instruct-fp16`, which is in the list of supported models [here](https://github.com/meta-llama/llama-stack/blob/c4d5d6bb91035f0904b100b64c6167aea2c5e2e2/llama_stack/providers/adapters/inference/ollama/ollama.py#L31) and still getting this error:

```
ValueError: `Llama3.1-8B-Instruct` not registered. Make sure there is an Inference provider serving this model.
```

Here is my `run.yaml`:

```
version: '2'
built_at: '2024-10-27T21:58:19.590865'
image_name: local-ollama
docker_image: null
conda_env: local-ollama
apis:
- inference
- safety
- agents
- memory
- datasetio
- scoring
- eval
- telemetry
providers:
  inference:
  - provider_id: remote::ollama
    provider_type: remote::ollama
    config:
      host: localhost
      port: 11434
  safety:
  - provider_id: meta-reference
    provider_type: meta-reference
    config:
      llama_guard_shield: null
      enable_prompt_guard: false
  agents:
  - provider_id: meta-reference
    provider_type: meta-reference
    config:
      persistence_store:
        namespace: null
        type: sqlite
        db_path: /home/geronimo/.llama/runtime/kvstore.db
  memory:
  - provider_id: meta-reference
    provider_type: meta-reference
    config: {}
  datasetio:
  - provider_id: meta-reference
    provider_type: meta-reference
    config: {}
  scoring:
  - provider_id: meta-reference
    provider_type: meta-reference
    config: {}
  eval:
  - provider_id: meta-reference
    provider_type: meta-reference
    config: {}
  telemetry:
  - provider_id: meta-reference
    provider_type: meta-reference
    config: {}
```

What am I doing wrong?

**Comment by yanxi0830** [comment]
@geronimo  Could you check what's the output from `ollama ps` and `llama-stack-client models list`?

**Comment by geronimo** [comment]
@yanxi0830, here you go.

ollama looks ok to me:
```
$ ollama ps
NAME                         ID              SIZE     PROCESSOR          UNTIL              
llama3.1:8b-instruct-fp16    4aacac419454    16 GB    46%/54% CPU/GPU    4 minutes from now  
```

But the llama stack client seems off. It's returning nothing, so I added debug logging, and this is what I see:

```
llama-stack-client models list
[2024-10-28 22:41:32 - httpx:82 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2024-10-28 22:41:32 - httpx:148 - DEBUG] load_verify_locations cafile='/home/geronimo/anaconda3/envs/stack/lib/python3.10/site-packages/certifi/cacert.pem'
[2024-10-28 22:41:32 - llama_stack_client._base_client:451 - DEBUG] Request options: {'method': 'get', 'url': '/models/list', 'headers': {'Accept': 'application/jsonl'}}
[2024-10-28 22:41:32 - llama_stack_client._base_client:986 - DEBUG] Sending HTTP Request: GET http://localhost:5000/models/list
[2024-10-28 22:41:32 - httpx:1038 - INFO] HTTP Request: GET http://localhost:5000/models/list "HTTP/1.1 200 OK"
[2024-10-28 22:41:32 - llama_stack_client._base_client:1025 - DEBUG] HTTP Response: GET http://localhost:5000/models/list "200 OK" Headers({'date': 'Tue, 29 Oct 2024 02:41:31 GMT', 'server': 'uvicorn', 'content-length': '2', 'content-type': 'application/json'})
```

**Comment by geronimo** [comment]
I figured it out. When I ran the llama stack server, the ollama server was not running any model. It was my mistake. Thanks for your help @yanxi0830.

**Comment by alexhegit** [comment]
> llama-stack-client

Hi Geronimo, I got the same issue. Could you show me what you did more to fix it?

I do ollama run `llama3.1:8b-instruct-fp16` before run the client test.
```
$ ollama run llama3.1:8b-instruct-fp16
pulling manifest
pulling 09cd6813dc2e... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  16 GB
pulling 948af2743fc7... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 1.5 KB
pulling 0ba8f0e314b4... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  12 KB
pulling 56bb8bd477a5... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   96 B
pulling daa7d15f6d0b... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  484 B
verifying sha256 digest
writing manifest
success
>>> /set verbose
Set 'verbose' mode.
>>> test
It looks like you're just testing the conversation! Is there anything else I can help you with or would you like to start a topic?

total duration:       7.426932596s
load duration:        6.432651477s
prompt eval count:    12 token(s)
prompt eval duration: 44.529ms
prompt eval rate:     269.49 tokens/s
eval count:           29 token(s)
eval duration:        948.677ms
eval rate:            30.57 tokens/s
>>> /show info
  Model
    architecture        llama
    parameters          8.0B
    context length      131072
    embedding length    4096
    quantization        F16

  Parameters
    stop    "<|start_header_id|>"
    stop    "<|end_header_id|>"
    stop    "<|eot_id|>"

  License
    LLAMA 3.1 COMMUNITY LICENSE AGREEMENT
    Llama 3.1 Version Release Date: July 23, 2024

```

But client run failed with 
```
$ python -m llama_stack.apis.inference.client localhost 5000
User>hello world, write me a 2 sentence poem about the moon
{"error": {"message": "400: Invalid value: `Llama3.1-8B-Instruct` not registered. Make sure there is an Inference provider serving this model."}}

```
Meanwhile, llamastack also report

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 206, in sse_generator
    async for item in await event_gen:
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 99, in chat_completion
    provider = self.routing_table.get_provider_impl(model)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routing_tables.py", line 131, in get_provider_impl
    raise ValueError(
ValueError: `Llama3.1-8B-Instruct` not registered. Make sure there is an Inference provider serving this model.

```

I use https://github.com/meta-llama/llama-stack/blob/main/distributions/ollama/gpu/run.yaml to start the llamastack.

**Comment by akhtet** [comment]
Based on @geronimo 's comment, I realised that the issue was that we needed to explicitly invoke `ollama run` before `llama stack run`. But it is also important to use matching model names between Llamastack and Ollama by checking in the code below: https://github.com/meta-llama/llama-stack/blob/c4d5d6bb91035f0904b100b64c6167aea2c5e2e2/llama_stack/providers/adapters/inference/ollama/ollama.py#L31

Overall, here is the sequence that worked for me in the end:
1. Pulled the right Ollama model image and also confirmed that it is supported by LlamaStack 
`ollama pull llama3.2:3b-instruct-fp16`
2. `ollama run llama3.2:3b-instruct-fp16` 
3. `llama stack run my-stack-name`
4. Invoke the llama stack inference API and refer the to the model name `Llama3.2-3B-Instruct`

**Comment by jerrygaoLondon** [comment]
It's a restriction/limitation when we attempt to run both Llama model and Llama stack via separated docker container and we have to set up Ollama server "locally" as [instructed](https://llama-stack.readthedocs.io/en/latest/getting_started/distributions/self_hosted_distro/ollama.html#setting-up-ollama-server). 

- https://llama-stack.readthedocs.io/en/latest/getting_started/distributions/self_hosted_distro/ollama.html#setting-up-ollama-server
- https://llama-stack.readthedocs.io/en/latest/getting_started/distributions/self_hosted_distro/ollama.html#running-llama-stack
