### ISSUE TITLE
Model ids that contains a colon throws error when trying to install on Windows

### ISSUE THREAD

**Issue by Sandstedt** [meta-llama/llama-stack#347]
### System Info

Windows 11
Python 3.12.7 (and 3.12.5 apparently depending on running py --version or python --version from PowerShell)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

When trying to download the new 3.2 models:
 ```
 llama model download --source meta --model-id Llama3.2-3B-Instruct:int4-spinquant-eo8    
 ```

 I get an directory error from Windows ( I assume as contains a colon):
```
 [WinError 267] The directory name is invalid: 'C:\\Users\\{USER}\\.llama\\checkpoints\\Llama3.2-3B-Instruct:int4-spinquant-eo8'
 ```
 

### Error logs

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jesan\AppData\Local\Programs\Python\Python312\Scripts\llama.exe\__main__.py", line 7, in <module>
  File "C:\Users\jesan\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_stack\cli\llama.py", line 44, in main
    parser.run(args)
  File "C:\Users\jesan\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_stack\cli\llama.py", line 38, in run
    args.func(args)
  File "C:\Users\jesan\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_stack\cli\download.py", line 177, in run_download_cmd
    _meta_download(model, meta_url, info)
  File "C:\Users\{username}\AppData\Local\Programs\Python\Python312\Lib\site-packages\llama_stack\cli\download.py", line 127, in _meta_download
    os.makedirs(output_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\jesan\\.llama\\checkpoints\\Llama3.2-3B-Instruct:int4-spinquant-eo8'
```

### Expected behavior

To be able to install the new models on Windows. I was able to install an older version that didn't have a colon in it's MODEL_ID, like:
```llama model download --source meta --model-id Llama-Guard-2-8B```

**Comment by Sandstedt** [comment]
Linked issue: https://github.com/meta-llama/llama-stack/issues/42
