### ISSUE TITLE
Llama-guard and remote::vllm name model name mismatch

### ISSUE THREAD

**Issue by stevegrubb** [meta-llama/llama-stack#365]
### System Info

Current torch on Linux system with nvidia hardware.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

There is a model name mismatch when using LLama-guard on a remote::vllm safety provider. I am using the container as setup by llama build with remote::vllm uncommented. I also apply the 2 fixes from issue #357. This is the safety section of the run.yaml file:
```
  safety:
  - provider_id: meta-reference
    provider_type: meta-reference
    config:
      llama_guard_shield:
        model: Llama-Guard-3-1B
        excluded_categories: []
      enable_prompt_guard: false
```
The vllm side presents "Llama-Guard-3-1B" as the model name.
$ curl http://localhost:8001/v1/models
{"object":"list","data":[{"id":"Llama-Guard-3-1B","object":"model","created":1730755194,"owned_by":"vllm","root":"meta-llama/Llama-Guard-3-1B"

Start up the llama stack server in the container. I see it check the safety server:
INFO:     192.168.1.8:41816 - "GET /v1/models HTTP/1.1" 200 OK
and it does not complain. It likes the model name. Next we test it like this from another terminal:
python -m llama_stack.apis.safety.client localhost 5000

The server responds:
  File "/usr/local/lib/python3.10/site-packages/openai/resources/completions.py", line 539, in create
    return self._post(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1058, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'object': 'error', 'message': 'The model `meta-llama/Llama-Guard-3-1B` does not exist.', 'type': 'NotFoundError', 'param': None, 'code': 404}

This response originates in the vllm server because the model's name is only Llama-Guard-3-1B. The question is why did the llama-stack server add meta-llama to the model name?
If I go change the safety vllm server to include the meta-llama in the served model name and restart both llama-stack and vllm, I see llama-stack server get the model name from the vllm system:
 INFO:     192.168.1.8:39438 - "GET /v1/models HTTP/1.1" 200 OK
no complaints, so I start the client test to llama-stack and we get this:

  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/safety/safety.py", line 77, in run_shield
    res = await shield.run(messages)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/safety/llama_guard.py", line 187, in run
    async for chunk in await self.inference_api.chat_completion(
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 99, in chat_completion
    provider = self.routing_table.get_provider_impl(model)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routing_tables.py", line 131, in get_provider_impl
    raise ValueError(
ValueError: `Llama-Guard-3-1B` not registered. Make sure there is an Inference provider serving this model.
INFO:     ::1:40424 - "POST /safety/run_shield HTTP/1.1" 400 Bad Request

There seems to be a naming mismatch for the safety model. Now, if I go into the run.yaml file and add meta-llama there so that they all match, I get a different traceback immediately on startup of llama-stack:

pydantic_core._pydantic_core.ValidationError: 1 validation error for SafetyConfig
llama_guard_shield.model
  Value error, Invalid model: meta-llama/Llama-Guard-3-1B. Must be one of ['Llama-Guard-3-11B-Vision', 'Llama-Guard-3-1B:int4', 'Llama-Guard-3-1B', 'Llama-Guard-3-8B', 'Llama-Guard-3-8B:int8'] [type=value_error, input_value='meta-llama/Llama-Guard-3-1B', input_type=str]

There's no combination of names that work. Based on the last error, it expects a name without meta-llama. Based on the second traceback it just wants the model name without meta-llama. So, I think the issue is the first traceback and why it adds meta-llama.

### Error logs

The original config full traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 240, in endpoint
    return await maybe_await(value)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 200, in maybe_await
    return await value
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 161, in run_shield
    return await self.routing_table.get_provider_impl(shield_type).run_shield(
  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/safety/safety.py", line 77, in run_shield
    res = await shield.run(messages)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/safety/llama_guard.py", line 187, in run
    async for chunk in await self.inference_api.chat_completion(
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 101, in <genexpr>
    return (chunk async for chunk in await provider.chat_completion(**params))
  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/adapters/inference/vllm/vllm.py", line 136, in _stream_chat_completion
    async for chunk in process_chat_completion_stream_response(
  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/utils/inference/openai_compat.py", line 149, in process_chat_completion_stream_response
    async for chunk in stream:
  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/adapters/inference/vllm/vllm.py", line 131, in _to_async_generator
    s = client.completions.create(**params)
  File "/usr/local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/resources/completions.py", line 539, in create
    return self._post(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
  File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1058, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'object': 'error', 'message': 'The model `meta-llama/Llama-Guard-3-1B` does not exist.', 'type': 'NotFoundError', 'param': None, 'code': 404}
```
The second config's full traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 240, in endpoint
    return await maybe_await(value)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 200, in maybe_await
    return await value
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 161, in run_shield
    return await self.routing_table.get_provider_impl(shield_type).run_shield(
  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/safety/safety.py", line 77, in run_shield
    res = await shield.run(messages)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/safety/llama_guard.py", line 187, in run
    async for chunk in await self.inference_api.chat_completion(
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 99, in chat_completion
    provider = self.routing_table.get_provider_impl(model)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routing_tables.py", line 131, in get_provider_impl
    raise ValueError(
ValueError: `Llama-Guard-3-1B` not registered. Make sure there is an Inference provider serving this model.
```

### Expected behavior

I was hoping it might work like shown here: https://github.com/meta-llama/llama-stack-apps

**Comment by TurboMa** [comment]
how do you build remote::vllm?

**Comment by stevegrubb** [comment]
@TurboMa on the remote system, you can just pip install it. For the llama-stack API server, you have to uncomment it like this: sed 's/        # /        /g' -i /usr/local/lib/python3.10/site-packages/llama_stack/providers/registry/inference.py when inside the container. It is not ready for general use. See above...

**Comment by stevegrubb** [comment]
One interesting observation, if I edit the table VLLM_SUPPORTED_MODELS in llama_stack/providers/adapters/inference/vllm/vllm.py and delete the "meta-llama" part from the Llama-Guard-3-1B line, it works.

**Comment by stevegrubb** [comment]
PR #384 fixes the issue.

**Comment by tnsai** [comment]
The issue appears to be back since today's commits.  Now getting: ""detail": "Invalid value: Model `Llama3.2-3B-Instruct` not served by any of the providers: remote::vllm-0, safety::vllm-0. Make sure there is an Inference provider serving this model."

When contributors alter config schema or model registration approach, they need to update documentation.

A sample run.yaml showing use of remote, inline providers, and use of a remote safety provider, would be nice for us poor conda users.

**Comment by ashwinb** [comment]
> When contributors alter config schema or model registration approach, they need to update documentation.

Absolutely. I think we are rushing through a series of changes this week, going to stabilize a package and then _much more_ careful updates and ensure error messages + documentation is clearer. This is on us and please hold us accountable!

**Comment by ashwinb** [comment]
> Also getting a warning about model_id conflicting with model namespace.

This is a warning coming from `pydantic` because we decided to (unfortunately) use `model_id` as a field in one of our BaseModel. We will get this warning silenced soon. cc @dineshyv

**Comment by ashwinb** [comment]
@tnsai 

> The issue appears to be back since today's commits. Now getting: ""detail": "Invalid value: Model Llama3.2-3B-Instruct not served by any of the providers: remote::vllm-0, safety::vllm-0. Make sure there is an Inference provider serving this model."

Getting back to your actual issue, could you share you run.yaml perhaps? And tell us what models the vLLM servers were serving?

**Comment by tnsai** [comment]
Apologies, was away for work.

My vLLM server is serving the following on 127.0.0.1:

- Full-fat fp16 meta-llama/Llama-3.2-3B-Instruct on port 5001 on 1 GPU
- Full-fat fp16 meta-llama/Llama-Guard-3-8B on port 5002 split over over 2 GPU instances

My redacted run.yaml is as follows:

```
version: '2'
built_at: '2024-11-14T04:00:04.239294'
image_name: remote-vllm-0
docker_image: null
conda_env: remote-vllm
apis:
- inference
- memory
- safety
- agents
- telemetry
providers:
  inference:
  - provider_id: remote::vllm-1
    provider_type: remote::vllm
    config:
      model: Llama3.2-3B-Instruct
      url: http://127.0.0.1:5001/v1
      max_tokens: 16384
      api_token: redacted
  - provider_id: safety::vllm
    provider_type: remote::vllm
    config:
      model: Llama-Guard-3-8B
      max_seq_len: 2048
      url: http://127.0.0.1:5002/v1
      api_token: redacted
  memory:
  - provider_id: inline::faiss-0
    provider_type: inline::faiss
    config:
      kvstore:
        namespace: null
        type: sqlite
        db_path: /home/redacted/.llama/runtime/faiss_store.db
  safety:
  - provider_id: inline::llama-guard-0
    provider_type: inline::llama-guard
    config:
      llama_guard_shield:
          model: Llama-Guard-3-8B
          excluded_categories: []
      enable_prompt_guard: false
  agents:
  - provider_id: inline::meta-reference
    provider_type: inline::meta-reference
    config:
      persistence_store:
        namespace: null
        type: sqlite
        db_path: /home/redacted/.llama/runtime/kvstore.db
  telemetry:
  - provider_id: inline::meta-reference-0
    provider_type: inline::meta-reference
    config: {}
metadata_store: null
models: []
shields: []
memory_banks: []
datasets: []
scoring_fns: []
eval_tasks: []
```
