### ISSUE TITLE
Ollama 4.0 vision and llama-stack token Invalid token for decoding

### ISSUE THREAD

**Issue by JoseGuilherme1904** [meta-llama/llama-stack#367]
### 🚀 The feature, motivation and pitch

ollama vision is new:
https://ollama.com/x/llama3.2-vision

providers:
  inference:
  - provider_id: remote::ollama
    provider_type: remote::ollama
    config:
      host: 127.0.0.1
      port: 11434

in lama_stack/providers/adapters/inference/ollama/ollama.py
OLLAMA_SUPPORTED_MODELS = {
    "Llama3.1-8B-Instruct": "x/llama:latest",
    "Llama3.1-70B-Instruct": "llama3.1:70b-instruct-fp16",
    "Llama3.2-1B-Instruct": "llama3.2:1b-instruct-fp16",
    "Llama3.2-3B-Instruct": "llama3.2:3b-instruct-fp16",
    "Llama-Guard-3-8B": "llama-guard3:8b",
    "Llama-Guard-3-1B": "llama-guard3:1b",
    **"Llama3.2-11B-Vision-Instruct": "x/llama:latest"**
}

Traceback (most recent call last):
  File "/home/guilherme/.local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 206, in sse_generator
    async for item in await event_gen:
  File "/home/guilherme/.local/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/agents.py", line 138, in _create_agent_turn_streaming
    async for event in agent.create_and_execute_turn(request):
  File "/home/guilherme/.local/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 179, in create_and_execute_turn
    async for chunk in self.run(
  File "/home/guilherme/.local/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 252, in run
    async for res in self._run(
  File "/home/guilherme/.local/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 427, in _run
    async for chunk in await self.inference_api.chat_completion(
  File "/home/guilherme/.local/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 101, in <genexpr>
    return (chunk async for chunk in await provider.chat_completion(**params))
  File "/home/guilherme/.local/lib/python3.10/site-packages/llama_stack/providers/adapters/inference/ollama/ollama.py", line 215, in _stream_chat_completion
    params = self._get_params(request)
  File "/home/guilherme/.local/lib/python3.10/site-packages/llama_stack/providers/adapters/inference/ollama/ollama.py", line 190, in _get_params
    "prompt": chat_completion_request_to_prompt(request, self.formatter),
  File "/home/guilherme/.local/lib/python3.10/site-packages/llama_stack/providers/utils/inference/prompt_adapter.py", line 46, in chat_completion_request_to_prompt
    return formatter.tokenizer.decode(model_input.tokens)
  File "/home/guilherme/.local/lib/python3.10/site-packages/llama_models/llama3/api/tokenizer.py", line 190, in decode
    return self.model.decode(cast(List[int], t))
  File "/home/guilherme/.local/lib/python3.10/site-packages/tiktoken/core.py", line 254, in decode
    return self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)
**KeyError: 'Invalid token for decoding: 128256'**

**Comment by ashwinb** [comment]
yeah that's a special token we need to correctly filter out for vision models. Let me look into this.

**Comment by ashwinb** [comment]
See https://github.com/meta-llama/llama-stack/pull/376/files -- it works now

**Comment by JoseGuilherme1904** [comment]
Thank you very much for your help.

While testing the image, an error occurs. Which version of HTTPX are you using? 

Thanks,
Guilherme
role='user' content=[ImageMedia(image=URL(uri='data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAAAAAAD/4gIcSUNDX1BST0ZJTEUAAQEAAAIMbGNtcwIQAABtbnRyUkdCIFhZWiAH3AABABkAAwApADlhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApkZXNjAAAA/AAAAF5jcHJ0AAABXAAAAAt3dHB0AAABaAAAABRia3B0AAABfAAAABRyWFlaAAABkAAAABRnWFlaAAABpAAAABRiWFlaAAABuAAAABRyVFJDAAABzAAAAEBnVFJDAAABzAAAAEBiVFJDAAABzAAAAEBkZXNjAAAAAAAAAANjMgAAAAAAAAAAAAAAAAAAAAAAAA...<more>...mited to): couch, coffee table, fireplace, etc\n\nReturn results in the following format:\n{\n    "description": 4 sentence architectural description of the image,\n    "items": list of furniture items present in the image\n}\n\nRemember to only list furniture items you see in the image. Just suggest item names without any additional text or explanations.\nFor eg. "Couch" instead of "grey sectional couch"\n\nReturn JSON as suggested, Do not return any other text or explanations.\n'] context=None
Traceback (most recent call last):
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/distribution/server/server.py", line 212, in sse_generator
    async for item in await event_gen:
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/agents/agents.py", line 138, in _create_agent_turn_streaming
    async for event in agent.create_and_execute_turn(request):
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 179, in create_and_execute_turn
    async for chunk in self.run(
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 252, in run
    async for res in self._run(
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 427, in _run
    async for chunk in await self.inference_api.chat_completion(
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/distribution/routers/routers.py", line 101, in chat_completion
    return (chunk async for chunk in await provider.chat_completion(**params))
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/inference/inference.py", line 220, in chat_completion
    request = await request_with_localized_media(request)
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/inference/inference.py", line 421, in request_with_localized_media
    m.content = await _convert_content(m.content)
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/inference/inference.py", line 415, in _convert_content
    return [await _convert_single_content(c) for c in content]
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/inference/inference.py", line 415, in <listcomp>
    return [await _convert_single_content(c) for c in content]
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/inference/inference.py", line 408, in _convert_single_content
    url = await convert_image_media_to_url(content, download=True)
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/utils/inference/prompt_adapter.py", line 77, in convert_image_media_to_url
    r = await client.get(media.image.uri)
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_client.py", line 1814, in get
    return await self.request(
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/guilherme/.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/guilherme/.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 188, in handle_async_request
    closing = self._assign_requests_to_connections()
  File "/home/guilherme/.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 264, in _assign_requests_to_connections
    origin = pool_request.request.url.origin
  File "/home/guilherme/.local/lib/python3.10/site-packages/httpcore/_models.py", line 289, in origin
    default_port = {
KeyError: b''

second error:

role='user' content=[ImageMedia(image=URL(uri='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABEwAAALMCAIAAABxA7APAAAAGXRFWHRTb2Z0d2FyZQBnbm9tZS1zY3JlZW5zaG907wO/PgAAACZ0RVh0Q3JlYXRpb24gVGltZQBxdWkgMjQgb3V0IDIwMjQgMTU6Mjk6MTJn2mNeAAEAAElEQVR4nOydd1wUR//HP3tHL0c7lK6gCApYAEWNCtYUETUxiSXRqEl8TEKCRk38aaJGfUysKE+KaZZEY574WBBN7FiiURELoCAKiDTlpJc77m7398feHde5g6Oo834Rczc7853Zndvd+ex857uUa9+xPWwrysrKQCAQCAQCgUAgEAhPPpxeDjVE4RAIBAKBQCAQCISnBk57N4BAIBAIBAKBQCAQTAkROQQCgUAgEAgEAuGpwqztq3R3d2/7SgmGU1xc3N5NIBA...<more>...mited to): couch, coffee table, fireplace, etc\n\nReturn results in the following format:\n{\n    "description": 4 sentence architectural description of the image,\n    "items": list of furniture items present in the image\n}\n\nRemember to only list furniture items you see in the image. Just suggest item names without any additional text or explanations.\nFor eg. "Couch" instead of "grey sectional couch"\n\nReturn JSON as suggested, Do not return any other text or explanations.\n'] context=None
Traceback (most recent call last):
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/distribution/server/server.py", line 212, in sse_generator
    async for item in await event_gen:
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/agents/agents.py", line 138, in _create_agent_turn_streaming
    async for event in agent.create_and_execute_turn(request):
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 179, in create_and_execute_turn
    async for chunk in self.run(
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 252, in run
    async for res in self._run(
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 427, in _run
    async for chunk in await self.inference_api.chat_completion(
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/distribution/routers/routers.py", line 101, in chat_completion
    return (chunk async for chunk in await provider.chat_completion(**params))
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/inference/inference.py", line 220, in chat_completion
    request = await request_with_localized_media(request)
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/inference/inference.py", line 421, in request_with_localized_media
    m.content = await _convert_content(m.content)
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/inference/inference.py", line 415, in _convert_content
    return [await _convert_single_content(c) for c in content]
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/inference/inference.py", line 415, in <listcomp>
    return [await _convert_single_content(c) for c in content]
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/impls/meta_reference/inference/inference.py", line 408, in _convert_single_content
    url = await convert_image_media_to_url(content, download=True)
  File "/home/guilherme/angular/llama/llama-stack/llama_stack/providers/utils/inference/prompt_adapter.py", line 77, in convert_image_media_to_url
    r = await client.get(media.image.uri)
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_client.py", line 1814, in get
    return await self.request(
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_client.py", line 1572, in request
    request = self.build_request(
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_client.py", line 346, in build_request
    url = self._merge_url(url)
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_client.py", line 376, in _merge_url
    merge_url = URL(url)
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_urls.py", line 117, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/tmp/a/llama/conda/envs/llamastack-rede/lib/python3.10/site-packages/httpx/_urlparse.py", line 158, in urlparse
    raise InvalidURL("URL too long")
httpx.InvalidURL: URL too long

**Comment by ashwinb** [comment]
@JoseGuilherme1904 can you tell me how to reproduce this failure?

**Comment by JoseGuilherme1904** [comment]
Hi [ashwinb](https://github.com/ashwinb), 

I'm involved in studying the AgentConfigToolFunctionCallToolDefinition. Once I complete this study, I plan to better describe the two issues I listed above.

Do I need to open a new topic to discuss the AgentConfigToolFunctionCallToolDefinition as I'm trying to configure a function, or can you help me here?

  tools = [
                AgentConfigToolFunctionCallToolDefinition(
                    type = "function_call",
                    function_name = "PesquisaWebCPF",
                    description = "Tendo um ou mais CPFs, utilize essa função para pesquisar todos os dados de um ou mais funcionários por CPF. Os dados retornados incluem dados cadastrais, financeiros, de férias, afastamentos, dependentes, endereço, telefones, e emails.",
                    parameters = {
                        "cpfs": {
                            "param_type": "array",
                            "description": "Uma lista de números de CPF para pesquisa (formato: XXXXXXXXXXX).",
                            "required": True
                        }
                    },
                    remote_execution = {
                        "url": "http://localhost/a.php",
                        "method": "GET",
                        "params": {
                            "cpfs": "{cpfs}"  
                        },
                        "headers": {
                            "Content-Type": "application/json",
                            "Authorization": ""   
                        },
                         
                    },
 
               )
            
            ]

estou tendo o seguinte erro:
Traceback (most recent call last):
  File "/home/guilherme/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/guilherme/.local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/guilherme/.local/lib/python3.10/site-packages/fastapi/routing.py", line 346, in app
    raise validation_error
fastapi.exceptions.RequestValidationError: [{'type': 'model_attributes_type', 'loc': ('body', 'agent_config', 'tools', 0, 'function_call', 'remote_execution', 'url'), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': 'http://localhost/a.php'}]
INFO:     127.0.0.1:46906 - "POST /agents/create HTTP/1.1" 400 Bad Request

**Comment by hardikjshah** [comment]
@JoseGuilherme1904 - are you still facing this issue ? Best if you open a new issue with the latest problem since code might have changed during this time. Thanks
