### ISSUE TITLE
Why can't I use my llama stack? Can anyone help me?

### ISSUE THREAD

**Issue by xie85** [meta-llama/llama-stack#373]
[2401213419@l12gpu30 llama3.2]$ llama stack run llapku --port 8080
Using config `/lustre/home/2401213419/.llama/builds/conda/llapku-run.yaml`
Resolved 19 providers
 inner-inference => meta-reference
 models => __routing_table__
 inference => __autorouted__
 inner-safety => meta-reference
 shields => __routing_table__
 safety => __autorouted__
 inner-memory => meta-reference
 memory_banks => __routing_table__
 memory => __autorouted__
 agents => meta-reference
 inner-datasetio => meta-reference
 datasets => __routing_table__
 datasetio => __autorouted__
 inner-scoring => meta-reference
 scoring_functions => __routing_table__
 scoring => __autorouted__
 eval => meta-reference
 telemetry => meta-reference
 inspect => __builtin__

Traceback (most recent call last):
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 368, in <module>
    fire.Fire(main)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 300, in main
    impls = asyncio.run(resolve_impls(config, get_provider_registry(), dist_registry))
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/llama_stack/distribution/resolver.py", line 191, in resolve_impls
    impl = await instantiate_provider(
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/llama_stack/distribution/resolver.py", line 287, in instantiate_provider
    impl = await fn(*args)
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/inference/__init__.py", line 16, in get_provider_impl
    from .inference import MetaReferenceInferenceImpl
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/inference/inference.py", line 18, in <module>
    from .generation import Llama
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/inference/generation.py", line 18, in <module>
    import torch
  File "/lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /lustre/home/2401213419/software/miniconda3/envs/llamastack-llapku/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
Error occurred in script at line: 40

**Comment by hardikjshah** [comment]
Can you please detail the steps you took and the config you have , else its difficult to debug and help. Thanks

**Comment by nightduck** [comment]
I'm having the same issue. System details:

```
(llama-stack) [me@host]$ lsb_release -a
LSB Version:    n/a
Distributor ID: RockyLinux
Description:    Rocky Linux 9.4 (Blue Onyx)
Release:        9.4
Codename:       n/a
(llama-stack) [me@host]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
(llama-stack) [me@host]$ echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib64:
```

To replicate the issue:

```
git clone git@github.com:meta-llama/llama-models.git
cd llama-models
conda create -n llama-stack python=3.10
conda activate llama-stack
pip install llama-stack
llama model download --source meta --model-id  meta-llama/Llama-3.2-1B-Instruct-QLORA_INT4_EO8
pip install torch fairscale fire blobfile
CHECKPOINT_DIR=~/.llama/checkpoints/Llama3.2-1B-Instruct-int4-qlora-eo8/
PYTHONPATH=$(git rev-parse --show-toplevel) torchrun llama_models/scripts/example_chat_completion.py $CHECKPOINT_DIR
```

Expected result: the example script should run

Actual result: 
```
(llama-stack) [oren.bell@cybermech1 llama-models]$ PYTHONPATH=$(git rev-parse --show-toplevel) torchrun llama_models/scripts/example_chat_completion.py $CHECKPOINT_DIR
Traceback (most recent call last):
  File "/home/oren.bell/.conda/envs/llama-stack/bin/torchrun", line 5, in <module>
    from torch.distributed.run import main
  File "/home/oren.bell/.conda/envs/llama-stack/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/oren.bell/.conda/envs/llama-stack/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
```

Funnily, I get the same output if I just run an random non-existent file

    PYTHONPATH=$(git rev-parse --show-toplevel) torchrun asdf

So it seems to be an issue with the environment where torchrun crashes before even invoking the script.

**Comment by hardikjshah** [comment]
I followed these steps 
```
git clone git@github.com:meta-llama/llama-models.git
cd llama-models
conda create -n llama-stack python=3.10
conda activate llama-stack
pip install llama-stack
pip install torch fairscale fire blobfile
torchrun llama_models/scripts/example_chat_completion.py --help
``` 

and it worked fine for me. I am on CUDA 12.2 though, and 

```
>>> torch.__version__
'2.5.1+cu124'`
```

Can you tell me if you have the same ?

**Comment by nightduck** [comment]
If I purge my environment and copy paste those steps exactly, I still get the linker error. `torch.__version__` won't run because torch fails to import (same linker error)

I was able to successfully execute `torchrun llama_models/scripts/example_chat_completion.py --help` after creating the conda environment like so

    conda create -n pytorch
    conda activate pytorch
    conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
    pip install llama-stack torch fairscale fire blobfile
    torchrun llama_models/scripts/example_chat_completion.py --help

I believe pytorch-cuda comes with its own CUDA binaries and installing them via conda fixes whatever linking issue I was getting
