### ISSUE TITLE
Create vLLM distribution

### ISSUE THREAD

**Issue by yanxi0830** [meta-llama/llama-stack#382]
### 🚀 The feature, motivation and pitch

We have support for vLLM inline/remote inference provider. We should create a distribution start up guide for vLLM in https://llama-stack.readthedocs.io/en/latest/getting_started/distributions/self_hosted_distro/index.html.

**Comment by terrytangyuan** [comment]
I believe we are still doing some testing on vLLM. Once we are done, we can probably help write up some guide on this. cc @stevegrubb

**Comment by stevegrubb** [comment]
I've been taking notes on how to run vllm. I have to say that it has changed since I started working on this. With PR #384 in place, it should be easier.

**Comment by tnsai** [comment]
@stevegrubb from the recent commits to main branch, can I assume vllm::remote is now working to some extent?

If so, are there any gotchas, e.g. edits required to site-packages files as per your previous comments elsewhere, or does the latest set of commits today cover any wrinkles?

**Comment by stevegrubb** [comment]
Yes, there are gotchas. Running vllm itself remotely is straightforward. The API server image has a lot of supporting commands that are needed for networking and mounting things. Also, routing is not mentioned nor setup by "llama stack config". As I was doing this, it remote::vllm was not a menu choice. So, I had to manually add the config options for url, api_token, and model. I don't know if the config option now walks you through that. Also, build prefixes the word "distribution" to the name of the image which mismatches what the llama stack program says to do for the next step.

I'm now trying to work through some examples in llama-stack-apps and am still running into mismatching names. I don't know if some of the changes in #384 need to be propagated to the apps repo. I'll reach out later after I verify I'm not causing the issue by having something misconfigured. Also, all the demos seem to use the 8B-instruct model. That might be too big for anyone with limited resources (given you also have to run a safety model, too). The 1B-instruct is better for demo purposes. It and the 1B-Guard model fit in a 4090RTX.

Now, if you want to run vllm inside the API server container, there 's a whole other set of problems. I'd say inline and remote need separate instructions. I really think remote::vllm is the way to go because you are not limited to the cuda runtime. You can choose between 7 or 8 supported accelerators.

**Comment by stevegrubb** [comment]
I opened issue #405. We still have model name mismatches.

**Comment by stevegrubb** [comment]
OK, to follow up, I updated to 0.0.53, rebuilt the container, and used the run-with-safety.yaml file and it all works. Finally! What is need to be done? There is https://github.com/meta-llama/llama-stack/blob/main/llama_stack/templates/remote-vllm/doc_template.md which has the important info but has a couple typos in it. But it is close to a working example.

In llama-stack-apps, the following demos do not work:
python -m examples.safety.llama_guard_demo localhost 5000
python examples/memory/client.py localhost 5000
python examples/safety/client.py localhost 5000

I suspect the API's have changed and they need updating.

**Comment by ashwinb** [comment]
Do you have an error log perhaps so I could quickly see?

**Comment by ashwinb** [comment]
> couple typos in it.

could you help us locate them please if you have them fresh on your mind?

**Comment by stevegrubb** [comment]
All demos (llama-stack-apps) document that the default port is 5000. If you use 5001, it deviates from the documentation. I see parts of the docs now have 5001 and a lot still has 5000. I'd suggest doing a grep -r 5001 and 5000 from the top of llama-stack, llama-stack-client-python, and llama-stack-apps and make sure they all match one or the other.

Also, the default port for vLLM is 8000. It is natural to use the next port 8001 for the safety model. So, I'd change 8081 to 8001 simply to avoid questions. Then there is the /app vs /root for configuration. The natural built-in location is /app. Of course that can all be changed in the code. But if you want to match all other documentation, /app/llamastack-run.yaml is the canonical config file.

As for the demos that don't work, do you want the tracebacks here or in another issue dedicated to that problem?

One last item, the run-with-safety.yaml has you to set max_tokens, but when the API server reaches out to verify the remote vLLM instance, it should use the max_tokens from the server itself since that is the ground truth.

```
$ curl http://localhost:8000/v1/models
{"object":"list","data":[{"id":"meta-llama/Llama-3.2-1B-Instruct","object":"model","created":1732282178,"owned_by":"vllm","root":"meta-llama/Llama-3.2-1B-Instruct","parent":null,"max_model_len":36864,"permission":[{"id":"modelperm-be9caa2819324a0ab0ff0cd9e02fff8f","object":"model_permission","created":1732282178,"allow_create_engine":false,"allow_sampling":true,"allow_logprobs":true,"allow_search_indices":false,"allow_view":true,"allow_fine_tuning":false,"organization":"*","group":null,"is_blocking":false}]}]}
```
max_model_len ^^^ has the value that goes in max_tokens. If it were configurable there's a good chance of a mismatch.

**Comment by stevegrubb** [comment]
Digging a little more into the resulting container...I ran
```llama stack build --template remote-vllm  --image-type docker```
The resulting image has a copy of vLLM inside it. Does it need one?

Also, it has a copy of torch independently from vLLM. I see a reference to "torch --index-url https://download.pytorch.org/whl/cpu" in llama_stack/providers/registry/safety.py and llama_stack/providers/registry/memory.py. Do they need torch?

If torch and vLLM are not needed for remote::vllm, that would make the API server image a lot smaller.

**Comment by stevegrubb** [comment]
I see the reported demo failures are fixed. Thanks! I also see that vLLM as a container dependency has been dropped. And I also see that torch is needed for embeddings  - so it has to stay. The only issue left is settling on 5000 or 5001 for the API server port and making everything match. I'd still recommend 8001 for the vLLM safety port.

**Comment by tnsai** [comment]
Can someone please provide a clear short set of sample commands for building and running v0.0.58 under Conda with remote vLLM being used for both inference and safety?

There have been a lot of changes in the past few weeks and running the Hero to Zero instructions, or the other docs floating around using distributions/remote-vllm/run-with-safety.yaml, and valid ENV vars results in errors  This appears to be a mismatch between the docs, the configs and what the latest code requires.

Am I correct in thinking that llama stack configure has also been deprecated?

**Comment by ashwinb** [comment]
@tnsai  can you check if https://llama-stack.readthedocs.io/en/latest/distributions/self_hosted_distro/remote-vllm.html#via-conda works for you? 

and yes `llama stack configure` has been deprecated since the wizard can be more confusing that helpful. it is better to tell the user about YAMLs and hope they can understand and edit them instead of a confusing TUI.

**Comment by tnsai** [comment]
Worth noting that running the instructions creates two directories in ~/.llama/distributions:

llamastack-remote-vllm - containing remote-vllm-run.yaml
remote-vllm - containing registry.db

Is that expected behaviour?

**Comment by tnsai** [comment]
What appears to be happening is that running llama stack expects datasetio, eval and scoring to be present in the run config but they aren't in the original build.yaml for vLLM.  Adding them in to build.yaml and re-building gets rid of the pydantic errors at runtime but then causes other errors, such as OpenAI authentication errors even though there is no OpenAI in use.

**Comment by tnsai** [comment]
@ashwinb I know you are super-busy but when you have time, can you check why v0.0.58 to 0.0.61 are not working using the remote-vllm templates?

**Comment by tnsai** [comment]
Bump.

Complete cleandown of anything Llama related (conda environments, previous distributions, ~/.llama, etc.) and followed documentation above.

Still errors:

`Traceback (most recent call last):
  File "/home/myuser/miniconda3/envs/llamastack-remote-vllm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/myuser/miniconda3/envs/llamastack-remote-vllm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/myuser/miniconda3/envs/llamastack-remote-vllm/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 354, in <module>
    main()
  File "/home/myuser/miniconda3/envs/llamastack-remote-vllm/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 286, in main
    impls = asyncio.run(construct_stack(config))
  File "/home/myuser/miniconda3/envs/llamastack-remote-vllm/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/myuser/miniconda3/envs/llamastack-remote-vllm/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/myuser/miniconda3/envs/llamastack-remote-vllm/lib/python3.10/site-packages/llama_stack/distribution/stack.py", line 186, in construct_stack
    impls = await resolve_impls(
  File "/home/myuser/miniconda3/envs/llamastack-remote-vllm/lib/python3.10/site-packages/llama_stack/distribution/resolver.py", line 180, in resolve_impls
    sorted_providers = topological_sort(
  File "/home/myuser/miniconda3/envs/llamastack-remote-vllm/lib/python3.10/site-packages/llama_stack/distribution/resolver.py", line 260, in topological_sort
    dfs((api_str, providers), visited, stack)
  File "/home/myuser/miniconda3/envs/llamastack-remote-vllm/lib/python3.10/site-packages/llama_stack/distribution/resolver.py", line 251, in dfs
    dfs((dep, providers_with_specs[dep]), visited, stack)
KeyError: 'datasetio'
++ error_handler 62
++ echo 'Error occurred in script at line: 62'
Error occurred in script at line: 62
++ exit 1
`

Using pip install of v0.0.63 and remote-vllm distribution.

Earlier versions v0.0.5x worked with my VLLM server.

What to do?

**Comment by tnsai** [comment]
I can now get the distribution running if I do a completely clean pip installation without using pip's cache and then manually add in the missing providers (compared to say the ollama distribution) to the remote-vllm-run.yaml.

Not fully tested yet (e.g. inference) but server is running and responding to model queries.

**Comment by tnsai** [comment]
Inference is confirmed as working.

@ashwinb @stevegrubb please update the vLLM run configs to include the full set of providers to prevent the errors, or improve the config handling.

Thanks.

**Comment by yanxi0830** [comment]
Closing as we have included a vLLM template: https://github.com/meta-llama/llama-stack/tree/main/llama_stack/templates/vllm-gpu
