### ISSUE TITLE
Model names mismatch with remote::vllm

### ISSUE THREAD

**Issue by stevegrubb** [meta-llama/llama-stack#405]
### System Info

It meets requirements.txt. Nvidia GeForce GPU.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

I'm using the remote::vllm setup in the run.yaml file:
```
providers:
  inference:
  - provider_id: infer-vllm
    provider_type: remote::vllm
    config:
      url: http://192.168.1.8:8000/v1
      api_token: fake
     model: Llama3.2-1B-Instruct
```
I check the model server using curl:

curl http://localhost:8000/v1/models
{"object":"list","data":[{"id":"Llama3.2-1B-Instruct","object":"model","created":1731083393,"owned_by":"vllm","root":"meta-llama/Llama-3.2-1B-Instruct",

This matchs. Check if it's supported:
$ llama model list | grep Llama3.2-1B-Instruct
| Llama3.2-1B-Instruct                    | meta-llama/Llama-3.2-1B-Instruct                    | 128K

Yes. But when I start the server API, just after enumerating the providers and before announcing the API's being served, is this:

Unknown model served by vllm: Llama3.2-1B-Instruct

On the remote::vllm server I see
INFO:     192.168.1.8:39968 - "GET /v1/models HTTP/1.1" 200 OK

So I know it reached out and got the same info posted by curl above. Now, I go into llama-stack-apps and edit examples/agents/hello.py to use Llama3.2-1B-Instruct. And then run

PYTHONPATH=. python examples/agents/hello.py localhost 5000           and we get
shield_call> No Violation
inference> Traceback (most recent call last):
  File "/home/sgrubb/llama-stack-apps/examples/agents/hello.py", line 72, in <module>
    fire.Fire(main)

On the API server, is this:
INFO:     ::1:59090 - "POST /agents/create HTTP/1.1" 200 OK
INFO:     ::1:59090 - "POST /agents/session/create HTTP/1.1" 200 OK
INFO:     ::1:59090 - "POST /agents/turn/create HTTP/1.1" 200 OK
role='user' content='Hello' context=None
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llama_stack/distribution/server/server.py", line 212, in sse_generator
and ends with:
ValueError: Model `Llama3.2-1B-Instruct` not served by any of the providers: infer-vllm, meta-reference. Make sure there is an Inference provider serving this model.

If I run the test from the previous issue:
python -m llama_stack.apis.safety.client localhost 5000

This works fine.

### Error logs

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llama_stack/distribution/server/server.py", line 212, in sse_generator
    async for item in await event_gen:
  File "/usr/local/lib/python3.11/site-packages/llama_stack/providers/impls/meta_reference/agents/agents.py", line 138, in _create_agent_turn_streaming
    async for event in agent.create_and_execute_turn(request):
  File "/usr/local/lib/python3.11/site-packages/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 179, in create_and_execute_turn
    async for chunk in self.run(
  File "/usr/local/lib/python3.11/site-packages/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 252, in run
    async for res in self._run(
  File "/usr/local/lib/python3.11/site-packages/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 427, in _run
    async for chunk in await self.inference_api.chat_completion(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_stack/distribution/routers/routers.py", line 99, in chat_completion
    provider = self.routing_table.get_provider_impl(model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_stack/distribution/routers/routing_tables.py", line 136, in get_provider_impl
    raise ValueError(
ValueError: Model `Llama3.2-1B-Instruct` not served by any of the providers: infer-vllm, meta-reference. Make sure there is an Inference provider serving this model.
```

### Expected behavior

Output like shown here:
https://github.com/meta-llama/llama-stack-apps

**Comment by stevegrubb** [comment]
New information, when I run this:

$ curl http://localhost:5000/models/list
[{"identifier":"Llama-Guard-3-1B","llama_model":"Llama-Guard-3-1B","metadata":{},"type":"model","provider_id":"meta-reference"},{"identifier":"Llama-Guard-3-1B","llama_model":"Llama-Guard-3-1B","metadata":{},"type":"model","provider_id":"safety-vllm"}]

It is not finding Llama3.2-1B-Instruct

There is something in ./llama_stack/providers/adapters/inference/vllm/vllm.py  called VLLM_SUPPORTED_MODELS. That needs to be deleted and use resolve_model(). It is imported by "from llama_models.sku_list import resolve_model". resolve_model has the list of all models. VLLM should not maintain one. In the 0.0.49 code, at line 73 is this:
```
    async def list_models(self) -> List[ModelDef]:
        vllm_to_llama_map = {v: k for k, v in VLLM_SUPPORTED_MODELS.items()}

        models = []
        for model in self.client.models.list():
            if model.id not in vllm_to_llama_map:

If changed to this:

        for model in self.client.models.list():
            m = resolve_model(model.id)
            if m is None:
                print(f"Unknown model served by vllm: {model.id}")
                continue
```
It does not produce this warning. What is resolved is not in the right format to be used later as I don't know enough details to do it right. But I can tell that it resolves the model correctly. The current git code has been changed a lot, but still uses the VLLM_SUPPORTED_MODELS.

**Comment by ashwinb** [comment]
https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/remote/inference/vllm/vllm.py

does not use any `VLLM_SUPPORTED_MODELS` at all so I am confused. Are you perhaps looking at older code or maybe this landed just after you looked at it?

**Comment by stevegrubb** [comment]
OK, I was applying PR 384 locally - which completely solved the safety model issue. I'll update everything in a couple days and retest.

**Comment by stevegrubb** [comment]
OK, I updated to 0.0.53 and used the run-with-safety.yaml. Set  the environmental variables. It works. This can be closed.
