### ISSUE TITLE
Mac failed run the Quick Start Guide

### ISSUE THREAD

**Issue by chrish2** [meta-llama/llama-stack#626]
### System Info

Mac M4 + Ollama + sample docker script

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

```
HOST = "localhost"  # Replace with your host
PORT = 5001       # Replace with your port
MODEL_NAME='meta-llama/Llama-3.2-3B-Instruct'

from llama_stack_client import LlamaStackClient

client = LlamaStackClient(base_url=f'http://{HOST}:{PORT}')
 
response = client.inference.chat_completion(
    messages=[
        {"role": "system", "content": "You are a friendly assistant."},
        {"role": "user", "content": "Write a two-sentence poem about llama."}
    ],
    model_id=MODEL_NAME,
)

print(response.completion_message.content)
```

### Error logs

```
INFO:     172.17.0.1:57444 - "POST /alpha/inference/chat-completion HTTP/1.1" 500 Internal Server Error
07:40:59.395 [INFO] [/alpha/inference/chat-completion] HTTP Request: POST http://host.docker.internal:11434/api/generate "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 187, in endpoint
    return await maybe_await(value)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 151, in maybe_await
    return await value
  File "/usr/local/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 123, in chat_completion
    return await provider.chat_completion(**params)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/remote/inference/ollama/ollama.py", line 221, in chat_completion
    return await self._nonstream_chat_completion(request)
  File "/usr/local/lib/python3.10/site-packages/llama_stack/providers/remote/inference/ollama/ollama.py", line 273, in _nonstream_chat_completion
    assert isinstance(r, dict)
AssertionError
```

### Expected behavior

Run smoothly

**Comment by ashwinb** [comment]
This bug has long been fixed but looks like there are stale packages out there. Can you tell me what exact docker command you used? Could you also list the docker image version by doing `docker image ls | grep llamastack`

**Comment by chrish2** [comment]
```
docker run -it \
  -p $LLAMA_STACK_PORT:$LLAMA_STACK_PORT \
  -v ~/.llama:/root/.llama \
  llamastack/distribution-ollama \
  --port $LLAMA_STACK_PORT \
  --env INFERENCE_MODEL=$INFERENCE_MODEL \
  --env OLLAMA_URL=http://host.docker.internal:11434
```

Docker image version: llamastack/distribution-ollama   latest    a7bb50aad98a

**Comment by ashwinb** [comment]
Oh no, `:latest` is pointing to an older docker. I am going to update the tag to point to the actual latest commit.

**Comment by ashwinb** [comment]
@chrish2 I updated latest to point to the correct version. Can you make sure you re-pull it?
